#Makefile generated by NAG Fortran Builder
#The following macros are machine specific
fblib = '../../../../../../Program Files (x86)/NAG/EFBuilder 7.0/lib'
NI_NAGFOR_Compiler = nagfor
NI_NAGFOR_CompOpts = -ideclient -abi=64 -g -C
NI_NAGFOR_NAGFORInfo = -gfb
NI_NAGFOR_CompOnly = -c
NI_NAGFOR_IFLAGS = 
NI_C_Compiler = nagfor =C
NI_C_CompOpts = -ideclient -abi=64 -g -Wc,-Wall
NI_C_CompOnly = -c
NI_IFLAGS = 
NI_CPP_Compiler = nagfor
NI_ALLOPTS = 
NI_Link = nagfor
NI_LibPath = -L'../../../../../../Program Files (x86)/NAG/EFBuilder 7.0/lib64' -L$(fblib) 
NI_LDFLAGS = 
NI_RM = fbrm 

#File extensions used in this Makefile
.SUFFIXES:
.SUFFIXES: .f90 .o 

#Output file
NI_OUTPUT = CSA_2021_NUMLAB.exe

#Target name
NI_TARGET = CSA_2021_NUMLAB.exe

#Object files
NI_OBJS =	 \
	frame.o

#Depend Object files
NI_DOBJS =	 \
	frame.o

#Prospective Module files
NI_MODS =	 \
    'globalvar.mod'

#Fortran Information files
NI_FIFS =	 \
	frame.fif

#Library files
NI_LIBS = 

#Dependencies
NI_EQ==
NI_SC=\;
frame.o:	frame.f90
globalvar.mod:	frame.f90

#Default make target rule
$(NI_TARGET):$(NI_OBJS)
	@echo @link
	$(NI_Link) -o $(NI_OUTPUT) $(NI_LibPath) @'CSA_2021_NUMLAB.mako' $(NI_LDFLAGS) $(NI_NAGFOR_CompOpts) $(NI_LIBS)

#Other rules
frame.o globalvar.mod:
	@echo @nagfor frame.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) frame.fif -c frame.f90

#Rebuild rule
all:clean $(NI_OBJS)
	@echo @link
	$(NI_Link) -o $(NI_OUTPUT) $(NI_LibPath) @'CSA_2021_NUMLAB.mako' $(NI_LDFLAGS) $(NI_NAGFOR_CompOpts) $(NI_LIBS)

#Clean rule
clean:
	$(NI_RM) $(NI_OUTPUT)
	$(NI_RM) frame.o
	$(NI_RM) $(NI_MODS)
	$(NI_RM) frame.fif
	$(NI_RM) fbvalwatch.vwi

#Clean all rule
clean_all:
	$(NI_RM) '*.exe' '*.a' '*.dll' '*.o' '*.mod' '*.fif' '*.bak' fbvalwatch.vwi
